In [25]:
import pandas as pd
xlsx2015 = 'https://github.com/sunilmurti/Final-Project/files/632770/2015.xlsx'
xlsx2014 = 'https://github.com/sunilmurti/Final-Project/files/632783/2014.xlsx'
xlsx2013 = 'https://github.com/sunilmurti/Final-Project/files/632792/2013.xlsx'
xlsx2012 = 'https://github.com/sunilmurti/Final-Project/files/632795/2012.xlsx'
xlsx2011 = 'https://github.com/sunilmurti/Final-Project/files/632850/2011.xlsx'
xlsx2010 = 'https://github.com/sunilmurti/Final-Project/files/632859/2010.xlsx'
xlsx2009 = 'https://github.com/sunilmurti/Final-Project/files/632860/2009.xlsx'
xlsx2008 = 'https://github.com/sunilmurti/Final-Project/files/632874/2008.xlsx'
xlsx2007 = 'https://github.com/sunilmurti/Final-Project/files/632876/2007.xlsx'
xlsx2006 = 'https://github.com/sunilmurti/Final-Project/files/632875/2006.xlsx'
xlsx2005 = 'https://github.com/sunilmurti/Final-Project/files/632873/2005.xlsx'
xlsx2004 = 'https://github.com/sunilmurti/Final-Project/files/632871/2004.xlsx'
xlsx2003 = 'https://github.com/sunilmurti/Final-Project/files/632870/2003.xlsx'
xlsx2002 = 'https://github.com/sunilmurti/Final-Project/files/632868/2002.xlsx'
xlsx2001 = 'https://github.com/sunilmurti/Final-Project/files/632872/2001.xlsx'
xlsx2000 = 'https://github.com/sunilmurti/Final-Project/files/632869/2000.xlsx'

yr2015 = pd.read_excel(xlsx2015)     
yr2014 = pd.read_excel(xlsx2014)
yr2013 = pd.read_excel(xlsx2013)
yr2012 = pd.read_excel(xlsx2012)     
yr2011 = pd.read_excel(xlsx2011)
yr2010 = pd.read_excel(xlsx2010)
yr2009 = pd.read_excel(xlsx2009)     
yr2008 = pd.read_excel(xlsx2008)
yr2007 = pd.read_excel(xlsx2007)
yr2006 = pd.read_excel(xlsx2006)     
yr2005 = pd.read_excel(xlsx2005)
yr2004 = pd.read_excel(xlsx2004)
yr2003 = pd.read_excel(xlsx2003)     
yr2002 = pd.read_excel(xlsx2002)
yr2001 = pd.read_excel(xlsx2001)
yr2000 = pd.read_excel(xlsx2000)

In [27]:
yr2015

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by State by City, 2015",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,City,Population,Violent\ncrime,Murder and\nnonnegligent\nmanslaughter,Rape\n(revised\ndefinition)1,Rape\n(legacy\ndefinition)2,Robbery,Aggravated\nassault,Property\ncrime,Burglary,Larceny-\ntheft,Motor\nvehicle\ntheft,Arson3
3,ALABAMA,Abbeville,2610,9,0,3,NaN,0,6,76,24,50,2,NaN
4,NaN,Adamsville,4414,25,1,3,NaN,5,16,330,38,278,14,NaN
5,NaN,Addison,748,4,0,0,NaN,0,4,28,11,15,2,NaN
6,NaN,Alabaster,31821,132,0,1,NaN,5,126,534,64,441,29,NaN
7,NaN,Albertville,21534,30,0,7,NaN,7,16,723,197,462,64,NaN
8,NaN,Alexander City,14854,221,0,10,NaN,10,201,652,145,474,33,NaN
9,NaN,Aliceville,2367,6,0,0,NaN,0,6,22,3,17,2,NaN
10,NaN,Andalusia,9096,73,1,9,NaN,2,61,528,85,425,18,NaN
11,NaN,Anniston,22306,607,8,44,NaN,79,476,1645,601,970,74,NaN
12,NaN,Arab,8330,43,0,7,NaN,2,34,516,106,385,25,NaN
13,NaN,Ardmore,1378,8,0,1,NaN,2,5,41,10,31,0,NaN
14,NaN,Argo,4214,1,0,1,NaN,0,0,36,14,18,4,NaN
15,NaN,Ashford,2170,5,0,0,NaN,0,5,63,5,54,4,NaN
16,NaN,Ashland,1972,16,0,1,NaN,0,15,52,10,41,1,NaN
17,NaN,Ashville,2265,4,0,1,NaN,0,3,17,5,12,0,NaN
18,NaN,Athens,25192,14,0,0,NaN,9,5,605,77,520,8,NaN
19,NaN,Atmore,9960,70,0,5,NaN,9,56,324,64,244,16,NaN
20,NaN,Attalla,5913,8,0,0,NaN,0,8,214,39,174,1,NaN
21,NaN,Auburn,62005,134,2,8,NaN,37,87,1621,266,1271,84,NaN
22,NaN,Bay Minette,9234,42,0,2,NaN,12,28,260,42,214,4,NaN
23,NaN,Bayou La Batre,2621,36,0,8,NaN,1,27,239,48,169,22,NaN
24,NaN,Bessemer,26828,475,7,15,NaN,117,336,2641,567,1869,205,NaN
25,NaN,Birmingham,212291,3707,79,159,NaN,1114,2355,13499,3146,8838,1515,145
26,NaN,Blountsville,1701,19,1,3,NaN,2,13,114,29,74,11,NaN
27,NaN,Boaz,9740,107,0,6,NaN,3,98,464,80,356,28,NaN
28,NaN,Brent,4866,16,2,1,NaN,3,10,105,21,81,3,NaN
29,NaN,Brewton,5389,49,0,3,NaN,7,39,228,27,179,22,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9378,NaN,Hanna,829,2,0,0,NaN,0,2,0,0,0,0,0
9379,NaN,Jackson,10668,19,0,4,NaN,1,14,168,15,138,15,1
9380,NaN,Kemmerer,2753,6,0,3,NaN,0,3,24,0,23,1,0
9381,NaN,Lander,7677,6,1,0,NaN,0,5,240,14,219,7,0
9382,NaN,Laramie,32375,43,1,10,NaN,0,32,526,60,442,24,3
9383,NaN,Mills,3750,19,0,2,NaN,2,15,113,33,71,9,0
9384,NaN,Moorcroft,1042,1,0,0,NaN,0,1,32,16,15,1,1
9385,NaN,Newcastle,3512,1,0,0,NaN,0,1,69,10,55,4,0
9386,NaN,Pine Bluffs,1150,7,0,0,NaN,1,6,8,5,3,0,0
9387,NaN,Powell,6429,18,0,3,NaN,1,14,138,15,121,2,1
9388,NaN,Rawlins,9227,30,1,1,NaN,0,28,240,32,194,14,6
9389,NaN,Riverton,11013,43,1,7,NaN,6,29,553,70,460,23,5
9390,NaN,Rock Springs,24314,86,0,31,NaN,2,53,498,62,412,24,2
9391,NaN,Saratoga,1694,1,0,0,NaN,1,0,12,4,7,1,0
9392,NaN,Sheridan,18030,25,0,2,NaN,3,20,390,57,311,22,0
9393,NaN,Sundance,1252,4,0,0,NaN,0,4,15,8,6,1,0
9394,NaN,Thermopolis,3024,1,0,1,NaN,0,0,12,1,7,4,0
9395,NaN,Torrington,6762,19,0,0,NaN,1,18,116,24,88,4,0
9396,NaN,Wheatland,3666,4,0,0,NaN,0,4,94,31,56,7,0
9397,NaN,Worland,5335,1,0,0,NaN,0,1,57,11,46,0,0
9398,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9399,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9400,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9401,"4 The population for the city of Mobile, Alaba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9402,5 This agency began the year submitting rape d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9403,6 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9404,7 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9405,8 The FBI determined that the agency did not f...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9406,9 Because of changes in the state/local agency...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9407,10 Arson offenses are reported by the Toledo F...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
yr2014

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by State by City, 2014",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,City,Population,Violent\ncrime,Murder and\nnonnegligent\nmanslaughter,Rape\n(revised\ndefinition)1,Rape\n(legacy\ndefinition)2,Robbery,Aggravated\nassault,Property\ncrime,Burglary,Larceny-\ntheft,Motor\nvehicle\ntheft,Arson3
3,ALABAMA,Abbeville,2643,8,0,1,NaN,0,7,85,22,52,11,NaN
4,NaN,Adamsville,4430,30,0,5,NaN,6,19,373,43,321,9,NaN
5,NaN,Addison,747,1,0,0,NaN,0,1,31,6,22,3,NaN
6,NaN,Alabaster,31568,58,1,9,NaN,11,37,612,68,526,18,NaN
7,NaN,Albertville,21655,23,1,5,NaN,8,9,756,230,454,72,NaN
8,NaN,Alexander City,14887,81,1,8,NaN,8,64,716,165,523,28,NaN
9,NaN,Aliceville,2403,10,0,0,NaN,0,10,43,9,32,2,NaN
10,NaN,Anniston,22567,536,4,42,NaN,77,413,1711,650,969,92,NaN
11,NaN,Arab,8369,46,0,13,NaN,3,30,567,140,382,45,NaN
12,NaN,Ardmore,1332,2,0,0,NaN,0,2,22,2,19,1,NaN
13,NaN,Argo,4200,4,0,2,NaN,0,2,38,13,20,5,NaN
14,NaN,Ashford,2164,5,0,0,NaN,0,5,57,12,41,4,NaN
15,NaN,Ashland,1967,11,0,0,NaN,0,11,52,9,42,1,0
16,NaN,Ashville,2262,13,0,3,NaN,0,10,68,26,37,5,NaN
17,NaN,Athens,24521,6,0,2,NaN,4,0,751,82,663,6,NaN
18,NaN,Atmore,10093,74,0,4,NaN,8,62,280,73,195,12,NaN
19,NaN,Auburn,59854,126,1,19,NaN,19,87,1654,257,1326,71,NaN
20,NaN,Bay Minette,9087,47,0,3,NaN,11,33,321,58,255,8,NaN
21,NaN,Bear Creek,1047,11,0,3,NaN,0,8,25,8,17,0,NaN
22,NaN,Birmingham,212115,3369,52,182,NaN,1051,2084,13929,3750,8743,1436,145
23,NaN,Blountsville,1712,10,0,2,NaN,0,8,69,24,36,9,NaN
24,NaN,Boaz4,9747,36,0,5,NaN,3,28,NaN,85,NaN,20,NaN
25,NaN,Brent,4878,13,0,2,NaN,1,10,81,7,66,8,NaN
26,NaN,Brewton,5445,37,0,2,NaN,5,30,239,45,180,14,NaN
27,NaN,Brighton,2885,46,0,2,NaN,2,42,161,50,94,17,NaN
28,NaN,Brilliant,886,3,0,0,NaN,0,3,26,8,15,3,NaN
29,NaN,Brookwood,1835,7,0,1,NaN,1,5,60,16,36,8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9337,NaN,Newcastle,3522,6,0,1,NaN,0,5,71,12,57,2,0
9338,NaN,Pine Bluffs,1159,3,0,0,NaN,0,3,20,8,12,0,0
9339,NaN,Powell,6516,17,0,4,NaN,1,12,169,28,135,6,1
9340,NaN,Rawlins,9160,26,0,1,NaN,0,25,199,15,166,18,1
9341,NaN,Riverton,11056,31,0,6,NaN,3,22,448,30,399,19,0
9342,NaN,Rock Springs,24431,67,1,20,NaN,5,41,540,71,432,37,3
9343,NaN,Saratoga,1667,2,0,0,NaN,0,2,8,0,4,4,0
9344,NaN,Sheridan,17920,39,1,3,NaN,1,34,404,69,314,21,3
9345,NaN,Sundance,1230,1,0,0,NaN,0,1,23,3,18,2,0
9346,NaN,Thermopolis,3047,1,0,1,NaN,0,0,22,5,16,1,3
9347,NaN,Torrington,6842,21,0,1,NaN,0,20,107,29,73,5,0
9348,NaN,Wheatland,3657,7,0,2,NaN,0,5,110,32,66,12,0
9349,NaN,Worland,5447,3,0,1,NaN,0,2,54,0,54,0,0
9350,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9351,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9352,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9353,4 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9354,"5 The population for the city of Mobile, Alaba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9355,6 This agency began the year submitting rape d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9356,7 Because of changes in the state/local agency...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9357,8 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9358,9 The FBI determined that the agency did not f...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9359,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9364,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9366,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
yr2013

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by State by City, 2013",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,City,Population,Violent\ncrime,Murder and\nnonnegligent\nmanslaughter,Rape\n(revised\ndefinition)1,Rape\n(legacy\ndefinition)2,Robbery,Aggravated\nassault,Property\ncrime,Burglary,Larceny-\ntheft,Motor\nvehicle\ntheft,Arson3,NaN,NaN,NaN
3,ALABAMA,Abbeville,2645,11,1,1,NaN,2,7,63,21,39,3,NaN,NaN,NaN,NaN
4,NaN,Adamsville,4481,19,1,0,NaN,7,11,321,58,252,11,NaN,NaN,NaN,
5,NaN,Addison,744,1,0,1,NaN,0,0,25,6,17,2,NaN,NaN,NaN,
6,NaN,Alabaster,31170,44,0,2,NaN,11,31,640,70,544,26,NaN,NaN,NaN,NaN
7,NaN,Alexander City,14692,119,2,16,NaN,12,89,661,121,510,30,NaN,NaN,NaN,NaN
8,NaN,Aliceville,2419,7,0,0,NaN,2,5,48,16,26,6,NaN,NaN,NaN,NaN
9,NaN,Andalusia,9079,34,1,4,NaN,6,23,491,95,379,17,NaN,NaN,NaN,NaN
10,NaN,Anniston,22648,461,5,39,NaN,78,339,1988,770,1120,98,NaN,NaN,NaN,NaN
11,NaN,Arab,8295,32,0,5,NaN,4,23,640,166,414,60,NaN,NaN,NaN,NaN
12,NaN,Ardmore,1304,2,0,0,NaN,0,2,31,7,23,1,NaN,NaN,NaN,NaN
13,NaN,Arley,353,3,0,0,NaN,0,3,27,12,11,4,NaN,NaN,NaN,NaN
14,NaN,Ashford,2177,2,0,0,NaN,0,2,54,8,46,0,NaN,NaN,NaN,NaN
15,NaN,Ashland,1926,9,0,0,NaN,1,8,63,24,35,4,NaN,NaN,NaN,NaN
16,NaN,Ashville,2239,10,0,1,NaN,0,9,88,35,48,5,NaN,NaN,NaN,NaN
17,NaN,Athens,23972,16,0,1,NaN,11,4,755,116,627,12,NaN,NaN,NaN,NaN
18,NaN,Atmore,10099,52,2,4,NaN,9,37,201,41,150,10,NaN,NaN,NaN,NaN
19,NaN,Auburn,57970,115,2,6,NaN,35,72,1930,346,1514,70,NaN,NaN,NaN,NaN
20,NaN,Bay Minette,8398,47,0,3,NaN,5,39,272,33,221,18,NaN,NaN,NaN,NaN
21,NaN,Bear Creek,1059,4,0,0,NaN,0,4,12,2,8,2,NaN,NaN,NaN,NaN
22,NaN,Bessemer,27240,527,3,15,NaN,161,348,3199,725,2265,209,NaN,NaN,NaN,NaN
23,NaN,Birmingham,212001,2852,63,178,NaN,969,1642,14157,4018,8661,1478,NaN,NaN,NaN,NaN
24,NaN,Blountsville,1697,6,0,3,NaN,0,3,71,14,49,8,NaN,NaN,NaN,NaN
25,NaN,Brent,4894,16,0,1,NaN,3,12,90,12,72,6,NaN,NaN,NaN,NaN
26,NaN,Brewton,5331,47,0,7,NaN,2,38,258,43,202,13,NaN,NaN,NaN,NaN
27,NaN,Bridgeport,2389,13,0,1,NaN,0,12,6,0,6,0,NaN,NaN,NaN,NaN
28,NaN,Brilliant,892,4,0,0,NaN,2,2,23,8,13,2,NaN,NaN,NaN,NaN
29,NaN,Butler,1850,6,0,0,NaN,1,5,40,15,22,3,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9275,NaN,Jackson,9918,62,0,NaN,9,17,36,231,20,199,12,0,NaN,NaN,NaN
9276,NaN,Kemmerer,2631,3,0,NaN,0,0,3,67,14,52,1,0,NaN,NaN,NaN
9277,NaN,Lander,7733,5,0,NaN,0,0,5,285,16,261,8,0,NaN,NaN,NaN
9278,NaN,Laramie,31940,37,1,NaN,10,3,23,670,70,562,38,2,NaN,NaN,NaN
9279,NaN,Lusk,1548,3,0,NaN,0,1,2,4,2,2,0,0,NaN,NaN,NaN
9280,NaN,Mills,3486,28,0,NaN,0,2,26,110,44,60,6,0,NaN,NaN,NaN
9281,NaN,Moorcroft,1026,1,0,NaN,0,0,1,32,1,30,1,0,NaN,NaN,NaN
9282,NaN,Newcastle,3465,8,0,NaN,3,0,5,84,16,66,2,0,NaN,NaN,NaN
9283,NaN,Pine Bluffs,1152,4,0,NaN,0,0,4,21,11,10,0,0,NaN,NaN,NaN
9284,NaN,Powell,6304,22,0,NaN,11,1,10,157,31,124,2,0,NaN,NaN,NaN
9285,NaN,Rawlins,9081,30,0,NaN,2,1,27,235,39,185,11,1,NaN,NaN,NaN
9286,NaN,Riverton,11057,45,0,NaN,4,5,36,563,41,498,24,0,NaN,NaN,NaN
9287,NaN,Rock Springs,24405,71,0,NaN,10,4,57,678,99,551,28,1,NaN,NaN,NaN
9288,NaN,Saratoga,1656,4,0,NaN,0,0,4,13,2,11,0,0,NaN,NaN,NaN
9289,NaN,Sheridan,17776,23,0,NaN,3,3,17,400,78,300,22,3,NaN,NaN,NaN
9290,NaN,Sundance,1221,0,0,NaN,0,0,0,11,2,7,2,0,NaN,NaN,NaN
9291,NaN,Thermopolis,3023,2,0,NaN,0,0,2,71,14,54,3,0,NaN,NaN,NaN
9292,NaN,Torrington,6797,18,0,NaN,1,0,17,121,33,85,3,0,NaN,NaN,NaN
9293,NaN,Wheatland,3644,11,0,NaN,0,0,11,114,21,85,8,0,NaN,NaN,NaN
9294,NaN,Worland,5441,7,0,NaN,0,0,7,47,2,45,0,0,NaN,NaN,NaN
9295,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9296,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9297,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9298,"4 The population for the city of Mobile, Alaba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9299,5 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9300,6 Because of changes in the state/local agency...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9301,7 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9302,8 The data collection methodology for the offe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9303,9 This agency began the year submitting rape d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9304,10 The FBI determined that the agency did not ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
yr2012

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by State by City, 2012",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,City,Population,Violent\ncrime,Murder and\nnonnegligent\nmanslaughter,Forcible\nrape,Robbery,Aggravated\nassault,Property\ncrime,Burglary,Larceny-\ntheft,Motor\nvehicle\ntheft,Arson1
3,ALABAMA,Abbeville,2715,22,0,1,3,18,57,16,38,3,NaN
4,NaN,Adamsville,4543,28,0,1,7,20,292,49,223,20,NaN
5,NaN,Addison,757,7,0,0,0,7,29,5,18,6,NaN
6,NaN,Alabaster,30923,49,0,2,6,41,683,65,585,33,NaN
7,NaN,Alexander City,14936,95,2,2,15,76,688,125,536,27,NaN
8,NaN,Aliceville,2448,9,0,0,0,9,60,19,39,2,NaN
9,NaN,Anniston,23051,504,5,14,92,393,2484,912,1501,71,NaN
10,NaN,Arab,8180,50,0,6,5,39,695,191,469,35,NaN
11,NaN,Ashford,2176,2,0,0,0,2,68,23,41,4,NaN
12,NaN,Ashland,2036,7,0,0,1,6,50,9,40,1,NaN
13,NaN,Ashville,2241,9,0,0,4,5,37,8,28,1,NaN
14,NaN,Athens,22681,31,1,1,14,15,850,166,666,18,NaN
15,NaN,Atmore,10188,63,1,2,7,53,343,82,242,19,NaN
16,NaN,Auburn,54785,132,3,13,25,91,1919,418,1450,51,NaN
17,NaN,Bay Minette,8249,49,2,2,8,37,354,47,297,10,NaN
18,NaN,Bayou La Batre,2565,47,0,0,5,42,228,77,123,28,NaN
19,NaN,Bessemer,27585,582,4,20,164,394,3329,873,2218,238,NaN
20,NaN,Birmingham,213266,3237,67,152,983,2035,14788,4704,9042,1042,117
21,NaN,Blountsville,1703,9,0,2,0,7,88,18,66,4,NaN
22,NaN,Brent,4945,17,1,0,1,15,64,16,46,2,NaN
23,NaN,Brewton,5398,67,0,1,7,59,296,56,224,16,NaN
24,NaN,Bridgeport,2431,21,0,1,0,20,35,7,25,3,NaN
25,NaN,Brundidge,2085,2,0,0,0,2,33,3,30,0,NaN
26,NaN,Butler,1870,8,1,0,0,7,43,13,27,3,NaN
27,NaN,Camp Hill,1019,21,0,1,0,20,45,25,16,4,NaN
28,NaN,Carbon Hill,2017,9,0,0,0,9,139,19,108,12,NaN
29,NaN,Carrollton,1006,1,0,0,0,1,23,7,16,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9471,NaN,Greybull,1889,6,0,0,0,6,12,4,8,0,0
9472,NaN,Hanna,847,4,0,0,0,4,0,0,0,0,0
9473,NaN,Hulett,390,2,0,1,0,1,7,5,1,1,0
9474,NaN,Jackson,9851,40,0,4,1,35,237,28,203,6,0
9475,NaN,Kemmerer,2690,0,0,0,0,0,36,2,32,2,0
9476,NaN,Lander,7681,9,1,3,0,5,261,30,225,6,2
9477,NaN,Laramie,31767,34,1,14,2,17,710,102,585,23,8
9478,NaN,Lusk,1594,2,0,0,0,2,4,1,2,1,0
9479,NaN,Mills,3555,13,0,0,0,13,97,25,68,4,1
9480,NaN,Moorcroft,1028,0,0,0,0,0,76,7,69,0,0
9481,NaN,Newcastle,3536,4,0,1,0,3,89,10,75,4,0
9482,NaN,Pine Bluffs,1157,10,0,1,0,9,20,6,13,1,0
9483,NaN,Powell,6486,24,0,13,1,10,211,50,160,1,2
9484,NaN,Rawlins,9337,25,0,9,0,16,258,39,204,15,3
9485,NaN,Riverton,11025,42,1,15,3,23,554,30,500,24,1
9486,NaN,Rock Springs,23566,89,2,15,1,71,623,61,546,16,2
9487,NaN,Saratoga,1702,1,0,0,0,1,15,1,14,0,0
9488,NaN,Sheridan,17771,26,1,4,0,21,461,95,350,16,3
9489,NaN,Sundance,1204,0,0,0,0,0,12,4,8,0,0
9490,NaN,Thermopolis,3045,6,0,0,0,6,45,6,37,2,1
9491,NaN,Torrington,6787,26,0,0,0,26,142,33,108,1,0
9492,NaN,Wheatland,3733,4,0,1,0,3,67,15,48,4,0
9493,NaN,Worland,5537,4,0,0,0,4,37,0,36,1,0
9494,1 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9495,"2 The population for the city of Mobile, Alaba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9496,3 Because of changes in the state/local agency...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9497,4 The FBI determined that the agency did not f...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9498,5 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9499,6 The data collection methodology for the offe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9500,7 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
yr2011

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,Offenses Known to Law Enforcement,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by State by City, 2011",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,City,Population,Violent\ncrime,Murder and\nnonnegligent\nmanslaughter,Forcible\nrape,Robbery,Aggravated\nassault,Property\ncrime,Burglary,Larceny-\ntheft,Motor\nvehicle\ntheft,Arson1,NaN,NaN,NaN,NaN,NaN
3,ALABAMA2,Abbeville,2701,13,0,1,2,10,65,12,51,2,1,NaN,NaN,NaN,NaN,NaN
4,NaN,Adamsville,4544,37,2,2,7,26,300,61,226,13,2,NaN,NaN,NaN,NaN,NaN
5,NaN,Addison,762,1,0,0,0,1,28,9,15,4,1,NaN,NaN,NaN,NaN,NaN
6,NaN,Alabaster,30498,59,2,1,10,46,656,86,541,29,1,NaN,NaN,NaN,NaN,NaN
7,NaN,Albertville,21262,43,0,7,5,31,917,247,616,54,0,NaN,NaN,NaN,NaN,
8,NaN,Alexander City,14947,138,0,12,11,115,768,206,527,35,0,NaN,NaN,NaN,NaN,NaN
9,NaN,Andalusia,9058,31,1,1,4,25,490,90,379,21,0,NaN,NaN,NaN,NaN,NaN
10,NaN,Anniston,23217,411,11,21,85,294,2323,996,1227,100,14,NaN,NaN,NaN,NaN,NaN
11,NaN,Arab,8089,63,1,3,6,53,676,165,460,51,13,NaN,NaN,NaN,NaN,NaN
12,NaN,Ardmore,1200,3,0,0,0,3,30,8,21,1,0,NaN,NaN,NaN,NaN,NaN
13,NaN,Argo,4091,8,0,1,0,7,43,18,21,4,0,NaN,NaN,NaN,NaN,NaN
14,NaN,Arley,359,1,0,0,0,1,19,3,15,1,0,NaN,NaN,NaN,NaN,NaN
15,NaN,Ashford,2158,9,0,0,0,9,82,30,50,2,1,NaN,NaN,NaN,NaN,NaN
16,NaN,Ashland,2047,13,0,2,0,11,42,8,31,3,0,NaN,NaN,NaN,NaN,NaN
17,NaN,Ashville,2223,6,2,0,0,4,35,5,29,1,1,NaN,NaN,NaN,NaN,NaN
18,NaN,Athens,22002,38,1,4,18,15,771,144,601,26,0,NaN,NaN,NaN,NaN,NaN
19,NaN,Atmore,10243,57,2,3,12,40,386,112,260,14,0,NaN,NaN,NaN,NaN,NaN
20,NaN,Auburn,53637,152,0,12,48,92,2143,550,1520,73,1,NaN,NaN,NaN,NaN,NaN
21,NaN,Bay Minette,8083,34,0,4,13,17,325,55,255,15,2,NaN,NaN,NaN,NaN,NaN
22,NaN,Bayou La Batre,2570,30,1,1,3,25,208,75,108,25,1,NaN,NaN,NaN,NaN,NaN
23,NaN,Bessemer,27588,464,10,23,126,305,3274,981,2011,282,16,NaN,NaN,NaN,NaN,NaN
24,NaN,Birmingham,213258,3163,54,182,1011,1916,17841,5806,10522,1513,123,NaN,NaN,NaN,NaN,NaN
25,NaN,Blountsville,1692,14,0,0,1,13,78,26,49,3,0,NaN,NaN,NaN,NaN,NaN
26,NaN,Boaz,9597,12,0,2,0,10,453,92,345,16,0,NaN,NaN,NaN,NaN,NaN
27,NaN,Brent,4971,22,0,1,2,19,120,33,77,10,1,NaN,NaN,NaN,NaN,NaN
28,NaN,Brewton,5434,90,0,5,1,84,276,52,215,9,1,NaN,NaN,NaN,NaN,NaN
29,NaN,Brighton,2959,0,0,0,0,0,1,0,0,1,4,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9294,NaN,Greybull,1862,10,0,1,0,9,12,3,8,1,0,NaN,NaN,NaN,NaN,NaN
9295,NaN,Hanna,848,4,0,0,0,4,1,0,1,0,0,NaN,NaN,NaN,NaN,NaN
9296,NaN,Hulett,386,1,0,0,0,1,4,0,4,0,0,NaN,NaN,NaN,NaN,NaN
9297,NaN,Jackson,9654,41,0,11,0,30,254,28,213,13,0,NaN,NaN,NaN,NaN,NaN
9298,NaN,Kemmerer,2677,1,0,0,0,1,52,2,49,1,0,NaN,NaN,NaN,NaN,NaN
9299,NaN,Lander,7547,9,0,1,0,8,243,32,204,7,0,NaN,NaN,NaN,NaN,NaN
9300,NaN,Laramie,31064,39,0,5,5,29,728,89,614,25,3,NaN,NaN,NaN,NaN,NaN
9301,NaN,Lusk,1580,1,0,0,0,1,6,2,3,1,0,NaN,NaN,NaN,NaN,NaN
9302,NaN,Mills,3489,23,1,0,0,22,127,61,64,2,0,NaN,NaN,NaN,NaN,NaN
9303,NaN,Moorcroft,1017,2,0,1,0,1,25,3,22,0,1,NaN,NaN,NaN,NaN,NaN
9304,NaN,Newcastle,3560,5,1,2,0,2,86,14,72,0,0,NaN,NaN,NaN,NaN,NaN
9305,NaN,Pine Bluffs,1138,10,0,0,0,10,39,7,27,5,0,NaN,NaN,NaN,NaN,NaN
9306,NaN,Powell,6365,16,0,3,2,11,199,17,182,0,3,NaN,NaN,NaN,NaN,NaN
9307,NaN,Rawlins,9333,44,0,1,0,43,278,40,224,14,0,NaN,NaN,NaN,NaN,NaN
9308,NaN,Riverton,10700,39,2,4,1,32,503,30,440,33,2,NaN,NaN,NaN,NaN,NaN
9309,NaN,Rock Springs,23221,76,0,15,4,57,651,69,556,26,2,NaN,NaN,NaN,NaN,NaN
9310,NaN,Saratoga,1704,0,0,0,0,0,26,5,21,0,0,NaN,NaN,NaN,NaN,NaN
9311,NaN,Sheridan,17584,31,0,3,1,27,473,58,400,15,3,NaN,NaN,NaN,NaN,NaN
9312,NaN,Sundance,1192,0,0,0,0,0,13,6,4,3,0,NaN,NaN,NaN,NaN,NaN
9313,NaN,Thermopolis,3033,0,0,0,0,0,45,3,42,0,0,NaN,NaN,NaN,NaN,NaN
9314,NaN,Torrington,6553,10,0,2,1,7,153,20,132,1,0,NaN,NaN,NaN,NaN,NaN
9315,NaN,Wheatland,3656,10,5,1,0,4,146,12,128,6,0,NaN,NaN,NaN,NaN,NaN
9316,NaN,Worland,5531,1,0,0,0,1,31,1,30,0,0,NaN,NaN,NaN,NaN,NaN
9317,"1 If a blank is presented in the arson column,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9318,2 Because of changes in the state/local agency...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9319,"3 The population for the city of Mobile, Alaba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9320,4 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9321,5 The FBI determined that the agency did not f...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9322,6 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9323,7 The data collection methodology for the offe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
yr2010

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by State by City, 2010",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,City,Population,Violent crime,Murder and nonnegligent manslaughter,Forcible rape,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson1
3,ALABAMA,Abbeville,2950,21,1,0,0,20,67,19,45,3,NaN
4,NaN,Adamsville,4796,10,0,3,2,5,294,21,250,23,NaN
5,NaN,Addison,714,0,0,0,0,0,33,3,26,4,NaN
6,NaN,Alabaster,30781,33,0,0,7,26,515,22,458,35,NaN
7,NaN,Albertville,20588,81,0,6,13,62,1112,346,710,56,NaN
8,NaN,Alexander City,15229,59,1,8,9,41,646,113,522,11,NaN
9,NaN,Aliceville,2423,12,0,1,0,11,51,10,35,6,NaN
10,NaN,Andalusia2,8946,24,0,3,0,21,NaN,NaN,NaN,11,NaN
11,NaN,Anderson,358,1,0,0,0,1,8,4,4,0,NaN
12,NaN,Anniston2,23703,NaN,3,23,76,NaN,2038,831,1107,100,NaN
13,NaN,Ardmore,1328,2,0,0,1,1,49,12,30,7,NaN
14,NaN,Argo,2005,3,0,1,0,2,21,10,8,3,NaN
15,NaN,Ariton,750,2,0,0,0,2,11,2,9,0,NaN
16,NaN,Arley,320,0,0,0,0,0,17,1,14,2,NaN
17,NaN,Ashford,2146,3,0,1,0,2,88,39,41,8,NaN
18,NaN,Ashland,1900,3,0,0,0,3,43,4,37,2,NaN
19,NaN,Ashville,2708,8,0,0,2,6,32,13,19,0,NaN
20,NaN,Athens,24989,34,0,4,12,18,717,129,564,24,NaN
21,NaN,Atmore,10182,49,0,2,5,42,335,62,252,21,NaN
22,NaN,Attalla,6621,60,0,4,4,52,297,65,226,6,0
23,NaN,Auburn,59651,83,3,4,13,63,1818,206,1559,53,NaN
24,NaN,Bayou La Batre,3253,23,0,1,0,22,172,62,90,20,NaN
25,NaN,Bear Creek,993,7,0,0,0,7,11,0,10,1,NaN
26,NaN,Bessemer,28881,289,5,18,83,183,2189,273,1753,163,NaN
27,NaN,Blountsville,2042,4,0,0,0,4,96,18,74,4,NaN
28,NaN,Boaz,8656,10,0,2,1,7,496,69,403,24,NaN
29,NaN,Brantley,912,0,0,0,0,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9290,NaN,Hanna,893,1,0,1,0,0,4,4,0,0,0
9291,NaN,Hulett,538,3,0,0,0,3,1,0,1,0,0
9292,NaN,Jackson,10301,41,0,13,1,27,235,23,204,8,0
9293,NaN,Kemmerer,2563,1,0,0,0,1,29,1,28,0,0
9294,NaN,Lander,7622,13,0,3,2,8,254,23,221,10,1
9295,NaN,Laramie,29742,42,0,10,1,31,667,113,521,33,4
9296,NaN,Lovell,2381,3,0,0,1,2,42,7,35,0,1
9297,NaN,Lusk,1465,7,0,2,0,5,12,2,9,1,0
9298,NaN,Mills,3707,17,0,0,0,17,99,32,61,6,0
9299,NaN,Moorcroft,961,0,0,0,0,0,22,5,17,0,1
9300,NaN,Newcastle,3505,3,0,2,0,1,115,23,92,0,0
9301,NaN,Pine Bluffs,1198,5,0,0,0,5,27,8,19,0,1
9302,NaN,Powell,5953,10,0,0,0,10,204,22,179,3,0
9303,NaN,Rawlins,8993,25,0,3,0,22,267,31,229,7,0
9304,NaN,Riverton,10613,43,2,5,7,29,535,58,462,15,0
9305,NaN,Rock Springs,21689,100,0,20,3,77,590,91,473,26,1
9306,NaN,Saratoga,1829,0,0,0,0,0,23,5,17,1,0
9307,NaN,Sheridan,18070,24,1,4,0,19,459,84,360,15,1
9308,NaN,Sundance,1387,0,0,0,0,0,14,3,9,2,0
9309,NaN,Thermopolis,3002,1,0,0,0,1,53,5,48,0,0
9310,NaN,Torrington,5816,18,0,1,0,17,161,28,127,6,0
9311,NaN,Wheatland,3290,4,0,2,0,2,161,51,106,4,0
9312,NaN,Worland,5157,9,0,0,0,9,30,6,23,1,0
9313,1 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9314,2 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9315,3 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9316,"4 The population for the city of Mobile, Alaba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9317,5 Because of changes in the state/local agency...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9318,6 The FBI determined that the agency did not f...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9319,7 The data collection methodology for the offe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
yr2009

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by State by City, 2009",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,City,Population,Violent crime,Murder and nonnegligent manslaughter,Forcible rape,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson1
3,ALABAMA,Abbeville,2932,9,0,1,0,8,53,18,33,2,NaN
4,NaN,Adamsville,4704,25,0,1,17,7,342,33,291,18,NaN
5,NaN,Addison,710,5,0,1,0,4,29,4,22,3,NaN
6,NaN,Alabaster,30002,41,0,2,12,27,635,82,522,31,NaN
7,NaN,Albertville,20078,82,0,11,12,59,928,233,659,36,NaN
8,NaN,Alexander City,15057,132,2,10,31,89,843,180,631,32,NaN
9,NaN,Aliceville2,2456,22,0,0,3,19,NaN,7,NaN,4,NaN
10,NaN,Andalusia,8994,54,1,5,7,41,484,61,408,15,NaN
11,NaN,Anniston,23598,584,5,27,113,439,2379,966,1258,155,NaN
12,NaN,Ardmore,1275,0,0,0,0,0,13,2,11,0,NaN
13,NaN,Ashford,2087,5,0,0,0,5,47,16,28,3,NaN
14,NaN,Ashland,1873,5,0,0,0,5,32,5,27,0,NaN
15,NaN,Ashville,2599,8,0,0,0,8,57,15,37,5,NaN
16,NaN,Athens,24261,32,0,3,18,11,802,132,630,40,NaN
17,NaN,Attalla,6514,57,1,4,3,49,253,42,204,7,NaN
18,NaN,Auburn2,57342,139,3,8,43,85,NaN,NaN,1779,38,NaN
19,NaN,Autaugaville,875,0,0,0,0,0,20,12,6,2,0
20,NaN,Baker Hill,313,0,0,0,0,0,1,0,1,0,NaN
21,NaN,Bear Creek,995,8,0,0,0,8,38,9,25,4,NaN
22,NaN,Berry,1184,0,0,0,0,0,3,1,1,1,NaN
23,NaN,Bessemer,28372,568,10,24,209,325,3813,1170,2416,227,NaN
24,NaN,Birmingham,227373,2812,65,198,1150,1399,18159,5019,11546,1594,135
25,NaN,Blountsville,2010,9,0,0,2,7,31,10,17,4,NaN
26,NaN,Boaz,8418,39,0,6,13,20,568,117,439,12,NaN
27,NaN,Brantley,910,3,0,0,0,3,9,1,8,0,NaN
28,NaN,Brent,4381,5,0,1,0,4,48,9,39,0,NaN
29,NaN,Bridgeport,2627,1,0,0,0,1,50,15,30,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9126,NaN,Guernsey,1065,0,0,0,0,0,7,3,4,0,0
9127,NaN,Hanna,866,1,0,0,0,1,1,0,1,0,0
9128,NaN,Jackson,9937,35,0,6,3,26,310,40,258,12,5
9129,NaN,Kemmerer,2449,6,0,0,0,6,35,5,30,0,0
9130,NaN,Lander,7304,7,0,2,0,5,228,22,204,2,0
9131,NaN,Laramie,27730,26,0,6,1,19,670,109,522,39,1
9132,NaN,Lovell,2268,4,0,1,0,3,67,11,54,2,0
9133,NaN,Lusk,1485,7,0,0,0,7,11,4,7,0,0
9134,NaN,Mills,3177,23,0,2,2,19,123,32,78,13,0
9135,NaN,Moorcroft,900,3,0,1,0,2,20,5,13,2,0
9136,NaN,Newcastle,3406,5,0,1,0,4,142,17,117,8,0
9137,NaN,Pine Bluffs,1155,7,0,0,0,7,15,5,8,2,0
9138,NaN,Powell,5540,23,0,8,2,13,195,23,168,4,1
9139,NaN,Rawlins,8716,23,0,1,2,20,310,36,254,20,1
9140,NaN,Riverton,10123,31,1,2,2,26,540,45,474,21,1
9141,NaN,Rock Springs,20391,96,0,9,6,81,758,78,644,36,1
9142,NaN,Saratoga,1763,3,0,0,0,3,21,9,9,3,0
9143,NaN,Sheridan,17350,43,1,3,1,38,488,107,356,25,2
9144,NaN,Sundance,1264,0,0,0,0,0,14,5,9,0,0
9145,NaN,Thermopolis,2951,10,0,0,0,10,38,6,30,2,0
9146,NaN,Torrington,5486,11,0,2,0,9,138,29,102,7,0
9147,NaN,Wheatland,3273,4,0,0,0,4,114,26,85,3,0
9148,NaN,Worland,4926,2,0,0,0,2,28,0,27,1,0
9149,1 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9150,2 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9151,3 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9152,"4 The population for the city of Mobile, Alaba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9153,5 The FBI determined that the agency did not f...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9154,6 Because of changes in the state/local agency...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9155,7 The data collection methodology for the offe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
yr2008

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by State by City, 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,City,Population,Violent crime,Murder and nonnegligent manslaughter,Forcible rape,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson1,NaN,NaN,NaN,NaN
3,ALABAMA,Abbeville,2939,16,0,1,2,13,79,21,54,4,NaN,NaN,NaN,NaN,NaN
4,NaN,Addison,715,5,0,0,0,5,34,10,24,0,NaN,NaN,NaN,NaN,NaN
5,NaN,Alexander City,14917,204,3,14,47,140,1024,190,790,44,NaN,NaN,NaN,NaN,NaN
6,NaN,Aliceville,2405,19,0,0,3,16,87,30,54,3,NaN,NaN,NaN,NaN,NaN
7,NaN,Andalusia,8689,56,0,8,4,44,477,94,361,22,NaN,NaN,NaN,NaN,NaN
8,NaN,Anniston,23620,572,13,30,179,350,2429,788,1478,163,NaN,NaN,NaN,NaN,NaN
9,NaN,Arab,7753,35,0,1,4,30,490,117,348,25,NaN,NaN,NaN,NaN,NaN
10,NaN,Ardmore,1209,1,0,0,0,1,20,3,15,2,NaN,NaN,NaN,NaN,NaN
11,NaN,Argo,1900,2,0,1,0,1,60,21,34,5,NaN,NaN,NaN,NaN,NaN
12,NaN,Ashford,2041,3,0,0,2,1,33,7,25,1,NaN,NaN,NaN,NaN,NaN
13,NaN,Ashland,1862,3,0,1,0,2,25,4,21,0,NaN,NaN,NaN,NaN,NaN
14,NaN,Ashville,2543,12,0,1,1,10,105,25,72,8,NaN,NaN,NaN,NaN,NaN
15,NaN,Athens,23432,53,0,4,19,30,849,141,675,33,NaN,NaN,NaN,NaN,NaN
16,NaN,Atmore,7391,77,3,5,19,50,542,108,403,31,NaN,NaN,NaN,NaN,NaN
17,NaN,Attalla,6515,60,0,5,7,48,363,47,308,8,NaN,NaN,NaN,NaN,NaN
18,NaN,Auburn,55649,181,2,17,56,106,2894,1022,1818,54,NaN,NaN,NaN,NaN,NaN
19,NaN,Autaugaville,877,0,0,0,0,0,15,8,7,0,NaN,NaN,NaN,NaN,NaN
20,NaN,Bay Minette,7710,67,0,7,15,45,391,56,318,17,NaN,NaN,NaN,NaN,NaN
21,NaN,Bayou La Batre,2716,22,1,0,10,11,275,73,184,18,NaN,NaN,NaN,NaN,NaN
22,NaN,Bear Creek,999,4,0,0,0,4,30,8,20,2,NaN,NaN,NaN,NaN,NaN
23,NaN,Berry,1183,0,0,0,0,0,5,1,1,3,NaN,NaN,NaN,NaN,NaN
24,NaN,Bessemer,28479,579,5,28,193,353,3716,1046,2392,278,NaN,NaN,NaN,NaN,NaN
25,NaN,Birmingham,228314,3249,82,212,1499,1456,20054,5153,12761,2140,134,NaN,NaN,NaN,NaN
26,NaN,Blountsville,1976,6,0,0,0,6,64,22,37,5,NaN,NaN,NaN,NaN,NaN
27,NaN,Boaz,8273,32,0,3,11,18,514,102,400,12,NaN,NaN,NaN,NaN,NaN
28,NaN,Brent,4384,21,0,1,3,17,114,26,86,2,NaN,NaN,NaN,NaN,NaN
29,NaN,Brighton,3247,2,0,0,1,1,11,4,7,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8753,NaN,Hanna,861,1,0,0,0,1,3,3,0,0,0,NaN,NaN,NaN,NaN
8754,NaN,Jackson,9753,44,0,11,1,32,415,57,354,4,0,NaN,NaN,NaN,NaN
8755,NaN,Kemmerer,2401,9,0,0,0,9,41,5,35,1,0,NaN,NaN,NaN,NaN
8756,NaN,Lander,7158,12,0,3,1,8,246,23,211,12,1,NaN,NaN,NaN,NaN
8757,NaN,Laramie,27260,29,0,5,2,22,811,112,663,36,4,NaN,NaN,NaN,NaN
8758,NaN,Lovell,2246,29,0,1,0,28,53,15,37,1,0,NaN,NaN,NaN,NaN
8759,NaN,Lusk,1327,1,0,0,0,1,31,7,19,5,0,NaN,NaN,NaN,NaN
8760,NaN,Mills,3169,7,0,0,0,7,113,11,96,6,0,NaN,NaN,NaN,NaN
8761,NaN,Moorcroft,858,3,1,1,0,1,41,20,20,1,0,NaN,NaN,NaN,NaN
8762,NaN,Newcastle,3334,12,0,0,0,12,135,20,108,7,0,NaN,NaN,NaN,NaN
8763,NaN,Pine Bluffs,1140,5,0,0,0,5,27,8,18,1,1,NaN,NaN,NaN,NaN
8764,NaN,Powell,5370,20,0,5,2,13,192,27,158,7,2,NaN,NaN,NaN,NaN
8765,NaN,Rawlins,8651,27,0,3,1,23,284,37,237,10,2,NaN,NaN,NaN,NaN
8766,NaN,Riverton,9907,33,1,10,3,19,460,31,414,15,5,NaN,NaN,NaN,NaN
8767,NaN,Rock Springs,19800,119,0,6,6,107,751,92,601,58,1,NaN,NaN,NaN,NaN
8768,NaN,Saratoga,1739,3,0,1,0,2,11,1,9,1,0,NaN,NaN,NaN,NaN
8769,NaN,Sheridan,16827,27,0,5,5,17,474,73,386,15,3,NaN,NaN,NaN,NaN
8770,NaN,Sundance,1211,1,0,1,0,0,28,6,22,0,0,NaN,NaN,NaN,NaN
8771,NaN,Thermopolis,2897,16,0,2,0,14,58,9,47,2,0,NaN,NaN,NaN,NaN
8772,NaN,Torrington,5396,11,0,3,0,8,158,25,131,2,0,NaN,NaN,NaN,NaN
8773,NaN,Wheatland,3327,4,0,2,0,2,99,12,82,5,2,NaN,NaN,NaN,NaN
8774,NaN,Worland,4901,16,0,0,0,16,38,10,27,1,0,NaN,NaN,NaN,NaN
8775,1 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8776,"2 The population for the city of Mobile, Alaba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8777,3 The FBI determined that the agency did not f...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8778,4 Because of changes in the state/local agency...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8779,5 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8780,6 The data collection methodology for the offe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8781,7 The data collection methodology for the offe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8782,8 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
yr2007

,Table 8,,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by State by City, 2007",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,City,Population,Violent crime,Murder and nonnegligent manslaughter,Forcible rape,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson1,NaN,NaN
3,ALABAMA,Abbeville,2955,8,0,1,1,6,105,16,83,6,NaN,NaN,NaN
4,NaN,Adamsville,4771,53,0,1,20,32,416,45,351,20,NaN,NaN,NaN
5,NaN,Addison,720,4,0,0,0,4,23,1,21,1,NaN,NaN,NaN
6,NaN,Alabaster,28904,33,1,0,18,14,659,68,545,46,NaN,NaN,NaN
7,NaN,Alexander City,15053,131,2,14,24,91,1016,182,784,50,NaN,NaN,NaN
8,NaN,Aliceville,2457,3,0,1,1,1,43,11,25,7,NaN,NaN,NaN
9,NaN,Andalusia,8727,40,0,3,7,30,381,63,300,18,NaN,NaN,NaN
10,NaN,Anniston,23736,541,9,20,188,324,2912,942,1723,247,NaN,NaN,NaN
11,NaN,Arab,7694,34,0,1,1,32,579,105,445,29,NaN,NaN,NaN
12,NaN,Ardmore,1145,0,0,0,0,0,41,9,27,5,NaN,NaN,NaN
13,NaN,Ariton,747,0,0,0,0,0,1,0,1,0,NaN,NaN,NaN
14,NaN,Ashford,1967,2,0,0,0,2,34,10,21,3,NaN,NaN,NaN
15,NaN,Ashland,1856,3,0,0,0,3,26,2,21,3,NaN,NaN,NaN
16,NaN,Ashville,2503,4,0,0,2,2,54,9,40,5,NaN,NaN,NaN
17,NaN,Atmore,7452,83,0,5,19,59,568,131,420,17,NaN,NaN,NaN
18,NaN,Auburn,53160,176,2,25,44,105,2559,630,1838,91,NaN,NaN,NaN
19,NaN,Autaugaville,885,2,0,0,0,2,27,12,13,2,NaN,NaN,NaN
20,NaN,Bay Minette,7674,54,1,3,9,41,376,73,281,22,NaN,NaN,NaN
21,NaN,Bayou La Batre,2761,25,0,1,4,20,325,70,229,26,NaN,NaN,NaN
22,NaN,Bear Creek,1016,6,0,0,0,6,24,2,19,3,NaN,NaN,NaN
23,NaN,Berry,1212,0,0,0,0,0,4,0,3,1,NaN,NaN,NaN
24,NaN,Bessemer,28217,502,10,34,195,263,3534,903,2373,258,NaN,NaN,NaN
25,NaN,Birmingham,227686,3320,86,229,1609,1396,19638,4864,12528,2246,221,NaN,NaN
26,NaN,Blountsville,1969,3,0,1,0,2,49,18,29,2,NaN,NaN,NaN
27,NaN,Boaz,8175,22,0,3,5,14,554,83,450,21,NaN,NaN,NaN
28,NaN,Brantley,906,1,0,0,0,1,47,10,37,0,NaN,NaN,NaN
29,NaN,Brent,4328,3,0,0,2,1,71,17,52,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8640,NaN,Hanna,855,0,0,0,0,0,3,0,1,2,0,NaN,NaN
8641,NaN,Jackson,9292,42,0,19,0,23,323,25,280,18,4,NaN,NaN
8642,NaN,Kemmerer,2508,3,0,0,0,3,25,1,24,0,1,NaN,NaN
8643,NaN,Lander,7066,15,0,0,0,15,213,24,178,11,0,NaN,NaN
8644,NaN,Laramie,25504,18,0,1,4,13,828,76,690,62,8,NaN,NaN
8645,NaN,Lovell,2279,4,1,0,0,3,28,0,28,0,0,NaN,NaN
8646,NaN,Lusk,1316,5,0,0,0,5,17,4,13,0,0,NaN,NaN
8647,NaN,Mills,2926,9,0,0,0,9,87,13,68,6,1,NaN,NaN
8648,NaN,Moorcroft,861,1,0,0,1,0,14,8,5,1,0,NaN,NaN
8649,NaN,Newcastle,3275,12,0,0,0,12,122,19,96,7,0,NaN,NaN
8650,NaN,Pine Bluffs,1142,5,0,1,0,4,20,6,13,1,0,NaN,NaN
8651,NaN,Powell,5388,11,0,4,0,7,202,17,179,6,3,NaN,NaN
8652,NaN,Rawlins,8572,54,1,5,3,45,377,53,307,17,1,NaN,NaN
8653,NaN,Riverton,9795,32,0,7,1,24,417,49,337,31,2,NaN,NaN
8654,NaN,Rock Springs,19432,135,3,9,16,107,851,154,643,54,6,NaN,NaN
8655,NaN,Saratoga,1721,1,0,0,0,1,22,0,22,0,0,NaN,NaN
8656,NaN,Sheridan,16507,9,0,2,3,4,372,58,297,17,4,NaN,NaN
8657,NaN,Sundance,1199,0,0,0,0,0,12,4,7,1,0,NaN,NaN
8658,NaN,Thermopolis,2912,17,0,0,0,17,81,10,70,1,0,NaN,NaN
8659,NaN,Torrington,5446,7,0,0,1,6,170,36,133,1,0,NaN,NaN
8660,NaN,Wheatland,3426,7,0,1,0,6,121,17,100,4,1,NaN,NaN
8661,NaN,Worland,4857,15,0,0,0,15,43,10,25,8,0,NaN,NaN
8662,1 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8663,"2 The population for the city of Mobile, Alaba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8664,3 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8665,4 It was determined that the agency did not fo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8666,5 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8667,6 The data collection methodology for the offe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8668,7 Because of changes in the state/local agency...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8669,8 The data collection methodology for the offe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
yr2006

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by State by City, 2006",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,City,Population,Violent crime,Murder and nonnegligent manslaughter,Forcible rape,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson1,NaN,NaN
3,ALABAMA,Abbeville,2990,11,0,1,0,10,92,23,66,3,NaN,NaN,NaN
4,NaN,Adamsville,4889,44,0,2,13,29,289,38,228,23,NaN,NaN,NaN
5,NaN,Alabaster,27766,27,0,0,8,19,650,39,561,50,NaN,NaN,NaN
6,NaN,Aliceville,2487,33,1,1,2,29,89,23,62,4,NaN,NaN,NaN
7,NaN,Andalusia,8770,49,0,8,8,33,532,120,389,23,NaN,NaN,NaN
8,NaN,Anniston,23956,521,14,29,161,317,3044,990,1812,242,NaN,NaN,NaN
9,NaN,Ardmore,1116,1,0,0,0,1,11,0,9,2,NaN,NaN,NaN
10,NaN,Ashford,1949,3,0,0,0,3,26,7,15,4,NaN,NaN,NaN
11,NaN,Ashville,2451,5,0,1,1,3,57,18,34,5,NaN,NaN,NaN
12,NaN,Atmore,7598,69,0,2,11,56,531,98,407,26,NaN,NaN,NaN
13,NaN,Auburn,50380,120,4,10,38,68,2151,537,1543,71,NaN,NaN,NaN
14,NaN,Autaugaville,873,0,0,0,0,0,29,13,15,1,NaN,NaN,NaN
15,NaN,Bayou La Batre,2750,16,0,2,5,9,274,69,171,34,NaN,NaN,NaN
16,NaN,Bear Creek,1030,2,0,0,0,2,15,2,12,1,NaN,NaN,NaN
17,NaN,Berry,1237,0,0,0,0,0,3,0,2,1,NaN,NaN,NaN
18,NaN,Bessemer,28900,493,5,37,200,251,3400,875,2218,307,NaN,NaN,NaN
19,NaN,Birmingham,233577,3175,104,220,1429,1422,19007,4813,12113,2081,228,NaN,NaN
20,NaN,Blountsville,1940,3,0,1,0,2,54,13,37,4,NaN,NaN,NaN
21,NaN,Boaz,7964,20,1,2,3,14,544,91,437,16,NaN,NaN,NaN
22,NaN,Brantley,917,2,0,0,0,2,23,7,15,1,NaN,NaN,NaN
23,NaN,Brent,4166,7,0,1,1,5,34,8,24,2,NaN,NaN,NaN
24,NaN,Brilliant,740,2,0,0,0,2,32,10,20,2,NaN,NaN,NaN
25,NaN,Butler,1796,0,0,0,0,0,8,6,1,1,NaN,NaN,NaN
26,NaN,Camden,2248,7,0,0,1,6,46,11,33,2,NaN,NaN,NaN
27,NaN,Centre,3346,0,0,0,0,0,28,3,24,1,NaN,NaN,NaN
28,NaN,Centreville,2530,4,0,0,1,3,25,7,18,0,NaN,NaN,NaN
29,NaN,Chatom,1189,1,0,0,1,0,22,4,18,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8235,NaN,Kemmerer,2589,3,0,0,0,3,34,5,29,0,0,NaN,NaN
8236,NaN,Lander,6975,16,0,0,0,16,231,27,196,8,3,NaN,NaN
8237,NaN,Laramie,26342,30,2,1,1,26,844,126,662,56,2,NaN,NaN
8238,NaN,Lovell,2303,4,0,0,0,4,41,2,39,0,0,NaN,NaN
8239,NaN,Lusk,1363,1,0,0,0,1,21,1,19,1,0,NaN,NaN
8240,NaN,Mills,2930,18,1,0,0,17,81,5,68,8,0,NaN,NaN
8241,NaN,Moorcroft,854,1,0,0,0,1,3,0,3,0,0,NaN,NaN
8242,NaN,Newcastle,3257,5,0,2,0,3,109,31,77,1,1,NaN,NaN
8243,NaN,Pine Bluffs,1175,1,0,0,0,1,34,15,18,1,0,NaN,NaN
8244,NaN,Powell,5347,12,0,3,0,9,213,24,185,4,3,NaN,NaN
8245,NaN,Rawlins,8755,40,0,2,4,34,399,47,332,20,2,NaN,NaN
8246,NaN,Riverton,9536,38,0,5,3,30,380,55,303,22,9,NaN,NaN
8247,NaN,Rock Springs,18982,136,1,10,5,120,800,146,601,53,12,NaN,NaN
8248,NaN,Saratoga,1733,9,0,0,0,9,41,2,38,1,0,NaN,NaN
8249,NaN,Sheridan,16516,16,0,1,1,14,482,68,398,16,1,NaN,NaN
8250,NaN,Sundance,1197,2,0,0,0,2,40,3,37,0,0,NaN,NaN
8251,NaN,Thermopolis,2938,3,0,0,0,3,121,0,119,2,0,NaN,NaN
8252,NaN,Torrington,5595,25,0,2,0,23,187,30,150,7,0,NaN,NaN
8253,NaN,Wheatland,3503,8,0,2,0,6,122,10,108,4,0,NaN,NaN
8254,NaN,Worland,5023,11,0,0,0,11,40,9,30,1,0,NaN,NaN
8255,1 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8256,"2 The population for the city of Mobile, Alaba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8257,3 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8258,4 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8259,5 It was determined that the agency did not fo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8260,6 Limited data for 2006 were available for Ill...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8261,7 The data collection methodology for the offe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8262,8 Because of changes in the state/local agency...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8263,"9 Due to an annexation, population and figures...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8264,10 The data collection methodology for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
yr2005

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by State by City, 2005",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,City,Population,Violent crime,Murder and nonnegligent manslaughter,Forcible rape,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson1
3,ALABAMA,Abbeville,3004,17,0,3,1,13,141,35,99,7,NaN
4,NaN,Adamsville,4929,40,0,3,12,25,386,51,307,28,NaN
5,NaN,Alexander City,15062,142,1,8,21,112,859,190,643,26,NaN
6,NaN,Aliceville,2499,23,0,0,3,20,95,25,64,6,NaN
7,NaN,Andalusia,8645,51,0,7,10,34,488,125,340,23,NaN
8,NaN,Anniston,23967,494,5,14,148,327,2955,870,1879,206,15
9,NaN,Ardmore,1094,2,0,0,1,1,42,13,27,2,NaN
10,NaN,Ariton,763,4,0,0,0,4,4,0,4,0,NaN
11,NaN,Ashford,1924,3,0,0,1,2,47,10,34,3,NaN
12,NaN,Ashland,1916,0,0,0,0,0,11,4,6,1,NaN
13,NaN,Ashville,2404,6,0,0,0,6,56,20,30,6,NaN
14,NaN,Atmore,7618,82,2,2,24,54,542,106,413,23,NaN
15,NaN,Attalla,6434,46,0,0,4,42,420,54,354,12,NaN
16,NaN,Auburn,48643,154,1,18,52,83,2172,464,1639,69,NaN
17,NaN,Autaugaville,861,6,0,1,1,4,25,9,15,1,NaN
18,NaN,Bay Minette,7867,44,0,1,11,32,343,59,270,14,NaN
19,NaN,Bayou La Batre,2758,20,0,1,3,16,218,54,143,21,NaN
20,NaN,Berry,1234,0,0,0,0,0,2,0,2,0,NaN
21,NaN,Bessemer,28902,555,3,24,234,294,3531,903,2336,292,NaN
22,NaN,Birmingham,234571,3449,104,241,1429,1675,18923,4933,11962,2028,136
23,NaN,Blountsville,1914,2,0,0,0,2,23,3,19,1,NaN
24,NaN,Boaz,7786,11,0,2,1,8,589,99,460,30,NaN
25,NaN,Brantley,905,5,0,1,0,4,19,5,14,0,NaN
26,NaN,Brent,4116,5,0,2,1,2,14,3,9,2,NaN
27,NaN,Brewton,5433,129,0,1,17,111,406,65,332,9,NaN
28,NaN,Brilliant,739,1,0,0,0,1,15,3,11,1,NaN
29,NaN,Brundidge,2330,7,0,0,2,5,64,17,46,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8156,NaN,Kemmerer,2575,3,0,0,0,3,39,4,35,0,0
8157,NaN,La Barge,421,0,0,0,0,0,4,0,2,2,0
8158,NaN,Lander,6926,15,0,0,0,15,266,31,228,7,0
8159,NaN,Laramie,26585,26,2,0,1,23,824,91,700,33,2
8160,NaN,Lovell,2323,6,0,3,0,3,41,5,35,1,0
8161,NaN,Lusk,1348,3,0,0,0,3,15,8,7,0,0
8162,NaN,Mills,2891,9,0,0,0,9,132,23,102,7,0
8163,NaN,Moorcroft,821,0,0,0,0,0,5,3,2,0,0
8164,NaN,Newcastle,3225,9,0,1,1,7,106,30,76,0,0
8165,NaN,Pine Bluffs,1187,4,0,0,1,3,41,8,31,2,0
8166,NaN,Powell,5279,14,0,5,0,9,233,37,193,3,1
8167,NaN,Rawlins,8680,34,0,3,4,27,422,57,332,33,1
8168,NaN,Riverton,9440,30,1,6,6,17,542,61,462,19,0
8169,NaN,Rock Springs,18848,110,1,10,7,92,800,151,600,49,5
8170,NaN,Saratoga,1719,13,0,0,0,13,59,3,56,0,0
8171,NaN,Sheridan,16206,22,0,2,1,19,450,40,392,18,0
8172,NaN,Sundance,1168,5,0,0,0,5,29,4,24,1,0
8173,NaN,Thermopolis,2969,4,0,1,0,3,95,5,89,1,0
8174,NaN,Torrington,5590,33,0,2,1,30,191,33,149,9,0
8175,NaN,Wheatland,3519,9,0,4,0,5,93,9,81,3,0
8176,NaN,Worland,5007,17,0,0,0,17,40,10,29,1,0
8177,1 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8178,"2 The population for the city of Mobile, Alaba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8179,3 Because of changes in the state/local agency...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8180,4 Savannah-Chatham Metropolitan is a city-coun...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8181,5 Limited data for 2005 were available for Ill...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8182,6 The data collection methodology for the offe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8183,7 After examining the data and making inquirie...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8184,8 After examining the data and making inquirie...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8185,9 After examining the data and making inquirie...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
yr2004

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by City 10,000 and over in Population, 2004",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,City by state,Population,Violent crime,Murder and non-negligent man-slaughter,Forcible rape,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson1,NaN,NaN,NaN,NaN,NaN,NaN
3,ALABAMA,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Albertville,18008,69,0,10,11,48,707,143,520,44,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Alexander City,15064,130,0,5,20,105,952,168,761,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Anniston,23905,479,6,34,133,306,2726,766,1765,195,23,NaN,NaN,NaN,NaN,NaN,NaN
7,Athens,19999,18,0,4,7,7,600,78,491,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Auburn,47230,147,2,29,48,68,2119,478,1583,58,NaN,NaN,,NaN,NaN,NaN,NaN
9,Bessemer,29298,488,2,24,197,265,3235,848,2107,280,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Birmingham,238167,3261,59,240,1369,1593,19477,5156,11970,2351,142,NaN,NaN,NaN,NaN,NaN,NaN
11,Cullman,14489,15,1,4,1,9,780,121,634,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Daphne,17813,23,0,3,8,12,361,70,264,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Decatur,54594,267,1,20,137,109,3921,710,3026,185,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Dothan,60429,281,9,59,124,89,3207,751,2310,146,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Enterprise,22004,33,1,4,8,20,361,99,224,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Eufaula,13740,44,1,6,18,19,605,63,512,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Fairfield,11996,123,0,14,58,51,1667,314,1236,117,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Fairhope,14230,19,0,4,10,5,665,112,516,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Florence,36086,168,1,7,39,121,1927,478,1401,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Fort Payne,13366,38,0,1,3,34,618,125,465,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Gadsden,37865,359,1,43,112,203,3548,810,2416,322,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Gardendale,12185,18,0,0,11,7,501,55,411,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Hartselle,12639,5,0,1,4,0,327,41,275,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Homewood,24559,133,0,7,73,53,1663,313,1219,131,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Hoover,65495,138,3,15,97,23,2117,388,1531,198,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Huntsville,165311,1109,6,93,363,647,10387,1924,7537,926,61,NaN,NaN,NaN,NaN,NaN,NaN
27,Jasper,14001,81,0,9,33,39,1002,122,807,73,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Leeds,10983,40,0,8,15,17,523,103,400,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Madison,34303,63,0,8,19,36,734,160,531,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2974,Stevens Point,24576,67,0,17,2,48,874,92,760,22,0,NaN,NaN,NaN,NaN,NaN,NaN
2975,Stoughton,12696,4,0,0,1,3,277,33,242,2,0,NaN,NaN,NaN,NaN,NaN,NaN
2976,Sun Prairie,23642,26,0,3,4,19,655,72,559,24,0,NaN,NaN,NaN,NaN,NaN,NaN
2977,Superior,27389,62,0,12,13,37,1553,257,1208,88,11,NaN,NaN,NaN,NaN,NaN,NaN
2978,Town of Menasha,15870,7,0,2,0,5,230,44,177,9,0,NaN,NaN,NaN,NaN,NaN,NaN
2979,Two Rivers,12321,17,0,8,1,8,227,25,196,6,1,NaN,NaN,NaN,NaN,NaN,NaN
2980,Watertown,22827,39,1,5,5,28,535,97,416,22,8,NaN,NaN,NaN,NaN,NaN,NaN
2981,Waupun,10521,4,0,3,0,1,179,22,153,4,0,NaN,NaN,NaN,NaN,NaN,NaN
2982,Wausau,37681,130,1,24,26,79,1382,275,1037,70,17,NaN,NaN,NaN,NaN,NaN,NaN
2983,Wauwatosa,46570,137,0,14,75,48,1958,239,1608,111,7,NaN,NaN,NaN,NaN,NaN,NaN
2984,West Allis,60596,154,0,15,66,73,2426,387,1828,211,29,NaN,NaN,NaN,NaN,NaN,NaN
2985,West Bend,29126,27,0,1,7,19,698,62,613,23,2,NaN,NaN,NaN,NaN,NaN,NaN
2986,Whitefish Bay,13941,7,0,0,5,2,168,28,135,5,0,NaN,NaN,NaN,NaN,NaN,NaN
2987,Whitewater,14215,20,0,7,0,13,281,37,236,8,0,NaN,NaN,NaN,NaN,NaN,NaN
2988,Wisconsin Rapids,18162,14,0,7,0,7,917,167,728,22,2,NaN,NaN,NaN,NaN,NaN,NaN
2989,WYOMING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2990,Casper,51166,108,0,7,13,88,2708,501,2064,143,11,NaN,NaN,NaN,NaN,NaN,NaN
2991,Cheyenne,54948,104,0,20,16,68,2504,324,2092,88,14,NaN,NaN,NaN,NaN,NaN,NaN
2992,Evanston,11495,19,0,1,0,18,560,53,481,26,0,NaN,NaN,NaN,NaN,NaN,NaN
2993,Gillette,22070,21,0,4,2,15,1018,98,898,22,14,NaN,NaN,NaN,NaN,NaN,NaN
2994,Green River,11663,43,0,0,0,43,458,118,319,21,5,NaN,NaN,NaN,NaN,NaN,NaN
2995,Laramie,27240,27,1,0,2,24,990,143,808,39,3,NaN,NaN,NaN,NaN,NaN,NaN
2996,Rock Springs,18594,168,2,7,13,146,957,168,710,79,12,NaN,NaN,NaN,NaN,NaN,NaN
2997,Sheridan,16185,20,1,3,4,12,489,45,423,21,0,NaN,NaN,NaN,NaN,NaN,NaN
2998,1 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2999,"2 The population for the city of Mobile, Alaba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3000,"3 Because of changes in reporting practices, a...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3001,4 Limited data for 2004 were available for Ill...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3002,5 The data collection methodology for the offe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3003,6 The data collection methodology for the offe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
yr2003

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by City 10,000 and over in Population, 2003",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,Violent crime,NaN,NaN,NaN,NaN,Property crime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,City by state,Population,Violent crime,Murder and non-negligent man-slaughter,Forcible rape,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson1,NaN,NaN,NaN,NaN,NaN,NaN
4,ALABAMA,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Alabaster,24956,23,0,2,3,18,202,23,160,19,0,NaN,NaN,NaN,NaN,NaN,NaN
6,Albertville2,17658,54,1,9,8,36,NaN,NaN,517,69,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Alexander City,14879,108,0,4,17,87,811,136,663,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Anniston,23868,502,2,28,155,317,3164,937,2011,216,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Athens,19612,12,0,0,7,5,668,97,546,25,0,NaN,NaN,NaN,NaN,NaN,NaN
10,Auburn,45533,146,1,22,50,73,1972,546,1347,79,NaN,NaN,,NaN,NaN,NaN,NaN
11,Birmingham,240176,3347,85,204,1352,1706,19574,4831,11934,2809,175,NaN,NaN,NaN,NaN,NaN,NaN
12,Cullman,14103,18,0,8,5,5,891,121,709,61,2,NaN,NaN,NaN,NaN,NaN,NaN
13,Daphne,17285,19,0,3,6,10,459,74,363,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Decatur,54112,221,4,11,117,89,3957,780,3001,176,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Dothan,59185,239,4,38,110,87,2917,670,2100,147,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Enterprise,21438,66,2,10,18,36,843,180,630,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Eufaula,13812,57,1,6,34,16,544,65,454,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Fairfield,12106,118,5,9,74,30,1643,252,1210,181,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Fairhope,13520,23,0,3,4,16,494,120,340,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Florence,35928,166,0,15,42,109,1601,304,1241,56,12,NaN,NaN,NaN,NaN,NaN,NaN
21,Fort Payne,13123,31,0,2,3,26,428,81,343,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Gadsden2,38087,NaN,6,21,78,NaN,3155,580,2312,263,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Gardendale,12043,30,1,3,17,9,461,64,363,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Hartselle,12213,6,0,0,2,4,318,39,267,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Helena,11438,1,0,1,0,0,43,4,38,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Homewood,24861,110,0,9,62,39,1525,286,1138,101,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Hoover,64469,242,0,18,113,111,1920,310,1480,130,NaN,NaN,NaN,,NaN,NaN,NaN
28,Hueytown,15462,70,2,0,40,28,479,112,325,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Huntsville,163052,988,19,84,316,569,9388,1740,6774,874,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,Waupun,10424,12,0,1,0,11,220,56,161,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2915,Wausau,37948,149,1,20,27,101,1703,344,1265,94,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2916,Wauwatosa,46980,133,0,10,72,51,1976,303,1565,108,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2917,West Allis,60985,166,3,16,84,63,2386,402,1781,203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2918,West Bend,28834,22,0,4,4,14,848,51,773,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2919,Whitefish Bay,14060,13,0,2,7,4,183,24,151,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2920,Whitewater,13989,25,0,3,2,20,345,26,311,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2921,Wisconsin Rapids,18318,11,0,3,1,7,866,155,685,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2922,WYOMING,NaN,NaN,,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2923,Casper,50279,125,4,15,15,91,2768,464,2141,163,21,NaN,NaN,NaN,NaN,NaN,NaN
2924,Cheyenne,53931,110,0,23,24,63,2465,258,2095,112,6,NaN,NaN,NaN,NaN,NaN,NaN
2925,Evanston,11506,8,0,2,1,5,551,43,489,19,0,NaN,NaN,NaN,NaN,NaN,NaN
2926,Gillette,21238,48,0,5,2,41,1114,93,983,38,10,NaN,NaN,NaN,NaN,NaN,NaN
2927,Green River,11687,38,0,0,3,35,374,54,312,8,0,NaN,NaN,NaN,NaN,NaN,NaN
2928,Laramie2,27022,51,1,4,3,43,946,139,761,46,5,NaN,NaN,NaN,NaN,NaN,NaN
2929,Rock Springs,18558,126,1,10,10,105,701,104,549,48,4,NaN,NaN,NaN,NaN,NaN,NaN
2930,Sheridan,16027,28,0,3,1,24,509,54,432,23,0,NaN,NaN,NaN,NaN,NaN,NaN
2931,1 If the FBI does not receive 12 months of ars...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2932,"2 Due to changes in reporting practices, annex...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2933,"3 The population for the city of Mobile, Alaba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2934,4 Forcible rape figures furnished by the state...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2935,5 Limited data for 2003 were available for Ill...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2936,"6 Louisville Metro, Kentucky, is a city-county...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2937,7 Aggravated assault figures furnished by thes...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2938,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2939,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2940,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2942,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2943,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
yr2002

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by City 10,000 and over in Population, 2002",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,City by state,Population,Crime Index,Modified Crime Index1,Murder and non-negligent man- ...,Forcible rape,Robbery,Aggravated assault,Burglary,Larceny-theft,Motor vehicle theft,Arson1,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ALABAMA,NaN,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Alabaster,22819,142,NaN,1,0,10,12,15,90,14,NaN,NaN,NaN,NaN,NaN,NaN
7,Albertville,17400,973,NaN,0,9,6,55,293,565,45,NaN,NaN,NaN,NaN,NaN,NaN
8,Alexander City,15141,987,NaN,2,8,23,81,129,724,20,NaN,NaN,NaN,NaN,NaN,NaN
9,Anniston,24491,3617,3635,7,35,164,366,900,1995,150,18,NaN,NaN,NaN,NaN,NaN
10,Athens,19135,761,NaN,2,1,10,10,119,584,35,NaN,NaN,NaN,NaN,NaN,NaN
11,Auburn,43368,2282,NaN,2,17,48,99,516,1506,94,NaN,NaN,,NaN,NaN,NaN
12,Birmingham,244972,21265,21476,65,239,1186,1697,4389,11640,2049,211,NaN,NaN,NaN,NaN,NaN
13,Cullman,14119,907,NaN,0,3,2,10,150,698,44,NaN,NaN,NaN,NaN,NaN,NaN
14,Daphne,16728,456,NaN,2,3,7,14,58,343,29,NaN,NaN,NaN,NaN,NaN,NaN
15,Decatur,54407,3810,NaN,4,17,105,91,773,2706,114,NaN,NaN,NaN,NaN,NaN,NaN
16,Dothan,58248,3072,NaN,1,40,90,81,568,2152,140,NaN,NaN,NaN,NaN,NaN,NaN
17,Enterprise,21366,909,NaN,1,9,20,43,151,631,54,NaN,NaN,NaN,NaN,NaN,NaN
18,Eufaula,14031,614,NaN,1,6,18,23,80,452,34,NaN,NaN,NaN,NaN,NaN,NaN
19,Fairfield,12491,1730,NaN,0,6,68,52,209,1155,240,NaN,NaN,NaN,NaN,NaN,NaN
20,Florence,36585,1869,1882,1,16,33,123,327,1327,42,13,NaN,NaN,NaN,NaN,NaN
21,Fort Payne,13052,581,NaN,0,5,4,41,79,450,2,NaN,NaN,NaN,NaN,NaN,NaN
22,Gadsden,39323,3934,NaN,4,31,97,584,741,2170,307,NaN,NaN,NaN,NaN,NaN,NaN
23,Gardendale,11729,475,NaN,0,1,3,12,67,374,18,NaN,NaN,NaN,NaN,NaN,NaN
24,Hartselle,12126,361,NaN,0,2,2,2,55,295,5,NaN,NaN,NaN,NaN,NaN,NaN
25,Homewood,25265,1560,NaN,1,9,61,32,229,1150,78,NaN,NaN,NaN,NaN,NaN,NaN
26,Hoover,63298,1916,NaN,1,19,82,105,254,1309,146,NaN,NaN,NaN,NaN,NaN,NaN
27,Hueytown,15500,481,NaN,0,5,27,21,92,292,44,NaN,NaN,NaN,NaN,NaN,NaN
28,Huntsville,159618,10167,10212,5,82,315,559,1714,6718,774,45,NaN,NaN,NaN,NaN,NaN
29,Leeds,10547,465,NaN,0,6,18,11,76,332,22,NaN,NaN,NaN,,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2962,Wisconsin Rapids,18701,905,910,0,4,1,1,151,724,24,5,NaN,NaN,NaN,NaN,NaN
2963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2964,WYOMING,NaN,,NaN,,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2966,Casper,50139,2725,2747,2,14,16,116,505,1936,136,22,NaN,NaN,NaN,NaN,NaN
2967,Cheyenne,53539,2476,2484,2,15,26,65,219,2061,88,8,NaN,NaN,NaN,NaN,NaN
2968,Evanston,11621,593,594,0,4,0,7,40,523,19,1,NaN,NaN,NaN,NaN,NaN
2969,Gillette,19842,1317,1323,0,4,4,27,112,1135,35,6,NaN,NaN,NaN,NaN,NaN
2970,Green River,11925,393,395,0,0,3,10,47,318,15,2,NaN,NaN,NaN,NaN,NaN
2971,Laramie,27475,1018,1021,0,5,0,141,125,693,54,3,NaN,NaN,NaN,NaN,NaN
2972,Rock Springs,18895,909,911,0,8,4,54,97,698,48,2,NaN,NaN,NaN,NaN,NaN
2973,Sheridan,15961,496,497,0,1,3,13,43,422,14,1,NaN,NaN,NaN,NaN,NaN
2974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2975,1 The Modified Crime Index is the sum of the s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2976,"agency or the state, no arson or Modified Cr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2977,"2 The population for the city of Mobile, Alaba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2978,"3 Due to changes in reporting practices, annex...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2979,4 Forcible rape figures furnished by the state...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2980,"UCR guidelines; therefore, the figures were ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2981,5 Limited data for 2002 were available for Ill...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2982,6 Aggravated assault figures furnished by thes...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2983,"Crime Index, and Modified Crime Index catego...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2984,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2985,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2986,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2988,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2989,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2990,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2991,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
yr2001

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by City 10,000 and over in Population, 2001",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,City by state,Population,Crime Index total,Modified Crime Index total1,Murder and non-negligent man- ...,Forcible rape,Robbery,Aggravated assault,Burglary,Larceny-theft,Motor vehicle theft,Arson1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ALABAMA2,NaN,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Alabaster,22707,246,NaN,2,1,11,15,23,175,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Alexander City,15066,1065,NaN,0,10,5,73,140,815,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Anniston,24370,3531,NaN,8,37,144,349,871,1920,202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Athens,19041,656,NaN,0,3,15,9,77,518,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Auburn,43154,2196,NaN,2,10,32,107,412,1534,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Birmingham,243762,21085,21336,73,206,1084,1664,4079,11928,2051,251,NaN,,NaN,NaN,NaN,NaN,NaN
13,Daphne,16645,525,NaN,0,4,4,9,49,437,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Dothan,57961,3105,NaN,3,43,83,58,562,2239,117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Enterprise,21260,1018,NaN,1,10,23,55,198,693,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Eufaula,13962,751,NaN,2,5,21,19,89,591,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Fairfield,12429,1759,NaN,12,3,83,58,249,1160,194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Florence,36405,1819,1830,2,12,36,103,376,1237,53,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Fort Payne,12988,592,NaN,1,3,4,14,89,477,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Gardendale,11671,432,NaN,0,2,8,21,42,331,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Hartselle,12066,398,NaN,0,1,2,2,74,308,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Helena,10336,100,NaN,0,1,1,8,18,70,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Homewood,25140,1845,NaN,0,10,54,41,205,1440,95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Hueytown,15424,626,NaN,1,1,15,29,115,419,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Huntsville,158830,11413,11454,15,109,345,570,1802,7802,770,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Leeds,10496,528,NaN,1,3,16,26,61,400,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Madison,29443,915,NaN,1,8,15,37,154,656,44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Millbrook,10426,378,NaN,2,3,13,2,168,176,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Mobile3,255551,19875,19967,42,95,840,552,4653,12284,1409,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2858,WYOMING,NaN,,NaN,,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2859,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2860,Casper,49708,2318,2365,2,20,23,111,435,1607,120,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861,Cheyenne,53080,2325,2334,0,14,15,52,268,1903,73,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2862,Evanston,11522,532,532,2,4,2,9,26,466,23,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2863,Gillette,19672,1220,1234,0,9,4,51,63,1063,30,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2864,Green River,11823,370,373,0,0,1,19,57,285,8,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2865,Laramie,27239,1120,1126,0,4,0,97,138,836,45,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2866,Rock Springs,18732,963,964,1,11,2,72,119,733,25,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2867,Sheridan,15825,490,490,0,5,2,15,57,393,18,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2868,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2869,1 The Modified Crime Index total is the sum of...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2870,"not received, there is no Modified Crime Ind...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2871,"2 Complete arson figures for 2001 for Alabama,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2872,"3 The population for the city of Mobile, Alaba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2873,"4 Due to changes in reporting practices, annex...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2874,5 The data for anthrax assaults were not avail...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2875,6 Forcible rape figures furnished by the state...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2876,"UCR guidelines; therefore, the figures were e...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2877,7 Limited data for 2001 were available for Ill...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2878,8 Aggravated assault figures were found to be ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2879,9 The murder and nonnegligent homicide figure ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2881,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2882,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2884,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2886,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2887,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
yr2000

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by City 10,000 and over in Population, 2000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,City by state,Population,Crime Index total,Modified Crime Index total1,Murder and non-negligent man- ...,Forcible rape,Robbery,Aggravated assault,Burglary,Larceny-theft,Motor vehicle theft,Arson,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ALABAMA2,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Alexander City,16450,870,NaN,3,8,15,47,119,658,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Anniston,26075,4066,4077,6,34,150,378,1122,2144,232,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Athens,20661,783,785,1,2,24,38,109,573,36,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Auburn,43354,2049,NaN,4,14,37,70,257,1613,54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Bessemer,31186,3930,NaN,6,21,174,246,802,2447,234,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Birmingham,253868,20749,20997,79,228,977,1663,4078,11975,1749,248,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Cullman,14454,837,NaN,-,4,10,25,136,621,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Daphne,16593,488,NaN,-,2,7,18,48,398,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Dothan,59415,3144,NaN,7,50,103,150,552,2159,123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Enterprise,21943,619,NaN,-,10,23,45,199,308,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Fairhope,13344,630,NaN,-,2,4,54,116,420,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Florence,39718,1811,NaN,-,7,26,104,295,1348,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Fort Payne,13044,622,NaN,-,2,5,8,98,507,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Gardendale,10499,425,NaN,-,-,1,16,51,322,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Homewood,22496,1807,NaN,-,6,62,36,194,1423,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Hoover,62491,2017,NaN,3,14,70,24,243,1514,149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Huntsville,181037,12239,12290,8,62,299,875,1882,8330,783,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Madison,27595,871,NaN,-,3,20,36,151,626,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Millbrook,11997,442,NaN,-,4,5,2,204,220,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Mobile3,243973,17614,17674,20,54,896,526,3609,10985,1524,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Montgomery,199149,16261,16373,31,113,605,814,3467,9795,1436,112,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Moody,10245,241,NaN,1,4,1,9,54,155,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Mountain Brook,20147,423,NaN,-,-,1,3,68,341,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2869,WYOMING,NaN,,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2870,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2871,Casper,49659,2182,2229,3,35,16,119,335,1558,116,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2872,Cheyenne,55519,2182,2195,2,20,21,60,182,1824,73,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2873,Evanston,11774,499,499,-,-,2,4,16,460,17,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2874,Gillette,20447,1049,1066,1,1,-,58,66,905,18,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2875,Green River,13268,451,453,-,-,-,14,54,374,9,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2876,Laramie,25641,822,825,-,5,1,69,97,624,26,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2877,Riverton,11101,503,507,1,9,5,17,82,376,13,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2878,Rock Springs,19799,1128,1130,1,17,6,82,109,886,27,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2879,Sheridan,15090,535,536,-,4,-,22,75,419,15,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2881,1 The Modified Crime Index total is the sum of...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2882,"2 Complete arson figures for 2000 for Alabama,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2883,"3 The population for the city of Mobile, Alaba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2884,"4 Due to changes in reporting practices, annex...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2885,5 Forcible rape figures furnished by the state...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2886,were not in accordance with national UCR gui...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2887,6 Limited data for 2000 were available for Ill...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2888,7 Aggravated assault figures were found to be ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2889,8 Forcible rape figures furnished by the state...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2890,Dashes (-) indicate a zero report.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2891,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2896,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2898,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN